version: 2
jobs:
  build:
    docker:
      - image: golang:1.6.4-jessie   # (1)
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker:   # (2)
          docker_layer_caching: true # (3)
      - restore_cache: # special step to restore the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Setup Dependencies
          command: npm install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      # - run: # run tests
      #     name: Run Test and Coverage
      #     command: |
      #       npm run build
      # - run:
      #       name: Set PLEO_ENVIRONMENT
      #       command: |
      #             echo "export COMMIT_MESSAGE=\"$(git log --format=oneline -n 1 $CIRCLE_SHA1)\"" >> $BASH_ENV
      # - run: sudo dockerd
      - run: sudo docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - run: sudo docker build --build-arg --quiet=false -t "hackdie/testing-docker:0.0.6" -f ./Dockerfile .
      - run: sudo docker tag "hackdie/testing-docker:0.0.6" "hackdie/testing-docker:latest"
      - run: sudo docker push hackdie/testing-docker:0.0.6
      - run: sudo docker push hackdie/testing-docker:latest

workflows:
  version: 2
  build-deploy:
    jobs:
      - build