version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache: # special step to restore the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Setup Dependencies
          command: npm install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      # - run: # run tests
      #     name: Run Test and Coverage
      #     command: |
      #       npm run build
      - run:
            name: Set PLEO_ENVIRONMENT
            command: |
                  echo "export COMMIT_MESSAGE=\"$(git log --format=oneline -n 1 $CIRCLE_SHA1)\"" >> $BASH_ENV
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - run: docker build --build-arg --quiet=false -t "hackdie/testing-docker:0.0.5" -f ./Dockerfile .
      - run: docker tag "hackdie/testing-docker:0.0.5" "hackdie/testing-docker:latest"
      - run: docker push hackdie/testing-docker:0.0.5
      # - run: sudo pip install awscli --upgrade
      - run: docker push hackdie/testing-docker:latest

workflows:
  version: 2
  build-deploy:
    jobs:
      - build